# theme: jekyll-theme-minimal
theme: jekyll-theme-hacker

title: Seekatar's Ruminations
description: A coder's view on life, the universe, and everything.

show_downloads: false
show_github: false

collections:
  authors:
    output: true
  popups:
  coding:
  photos:

defaults:
- scope:
    path: ""
    type: "authors"
  values:
    layout: "author"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
  values:
    layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag