# theme: jekyll-theme-minimal
theme: jekyll-theme-hacker

title: Seekatar's Ruminations
description: A coder's view on life, the universe, and everything.

imageWidth: "75%"
coverWidth: "50%"

show_downloads: false
show_github: false

collections:
  authors:
    output: true
  popups:
  coding:
  photos:

defaults:
- scope:
    path: ""
    type: "authors"
  values:
    layout: "author"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    author: "seektar"
- scope:
    path: ""
    type: "popups"
  values:
    layout: "post"
- scope:
    path: ""
  values:
    layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: seekatar-github-io

# url: my_website_url
mybaseurl: https://seekatar.github.io
