# docker build -f ./Dockerfile-base-onbuild -t base-onbuild --progress plain .
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

# ... other setup for build
RUN echo "This is the only instruction in this base image"

ONBUILD RUN --mount=type=secret,id=nugetPassword,env=nugetPassword \
            dotnet nuget add source "https://myorg.pkgs.visualstudio.com/_packaging/MySource/nuget/v3/index.json" \
                -n MylNuget -u ignoredWhenUsingPAT --store-password-in-clear-text \
                -p ${nugetPassword}
